FROM 10.10.89.157/tools/python:3.12.8-slim-bookworm

ENV TZ="Asia/Shanghai" \
    HOME="/naispilot" \
    CONFIG_DIR="/config" \
    STREAMLIT_SERVER_PORT="8502" \
    REDIS_HOST="redis"\
    REDIS_PASSWD="neuadminredis"\
    APP_ENV="dev"\
    TERM="xterm" \
    PUID=0 \
    PGID=0

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        p7zip-full \
        unzip \
        tar \
        gzip \
        bzip2 \
        unrar-free && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -r naispilot -g 918 \
    && useradd -r naispilot -g naispilot -d ${HOME} -s /bin/bash -u 918 \
    && mkdir -p ${HOME}

COPY . .

RUN pip install --timeout 60 -r requirements.txt --trusted-host oscoe.neusoft.com --index-url http://oscoe.neusoft.com:8081/repository/neusoft-pypi-proxy/simple
RUN chmod +x /app/entrypoint.sh

EXPOSE 8001
EXPOSE 8502

VOLUME [ "/config", "/logs" ]
ENTRYPOINT [ "/app/entrypoint.sh" ]
