import ollama
import os
import json
import numpy as np
from numpy.linalg import norm
import json
from src.utils import coreData, settings
import time
import asyncio
from concurrent.futures import ThreadPoolExecutor

client = ollama.Client(host="http://10.146.12.2:11434")

# open a file and return paragraphs
def save_file(filename:str, data:str):
    os.path.join('embeddings/', filename)
    with open(filename, "w") as f:
        f.write(data)    

def parse_file(data):    
    paragraphs = []
    buffer = []
    for line in data.split('\n'):
        line = line.strip()
        print(line)
        if line:
            buffer.append(line)
        elif len(buffer):
            paragraphs.append((" ").join(buffer))
            buffer = []
    if len(buffer):
        paragraphs.append((" ").join(buffer))
    return paragraphs

def save_embeddings(filename, embeddings):
    # create dir if it doesn't exist
    if not os.path.exists("embeddings"):
        os.makedirs("embeddings")
    # dump embeddings to json
    with open(f"embeddings/{filename}.json", "w") as f:
        json.dump(embeddings, f)


def load_embeddings(filename):
    # check if file exists
    if not os.path.exists(f"embeddings/{filename}.json"):
        return False
    # load embeddings from json
    with open(f"embeddings/{filename}.json", "r") as f:
        return json.load(f)


def get_embeddings(filename, modelname, chunks):
    # check if embeddings are already saved
    if (embeddings := load_embeddings(filename)) is not False:
        return embeddings

    embeddings = [
        client.embeddings(model=modelname, prompt=chunk)["embedding"]
        for chunk in chunks
    ]
    # save embeddings
    save_embeddings(filename, embeddings)
    return embeddings


# find cosine similarity of every chunk to a given embedding
def find_most_similar(needle, haystack):
    needle_norm = norm(needle)
    similarity_scores = [
        np.dot(needle, item) / (needle_norm * norm(item)) for item in haystack
    ]
    return sorted(zip(similarity_scores, range(len(haystack))), reverse=True)

def get_modes():
    try:
        setting = settings.get_ollama_settings()
        timeout = setting.timeout
        client = ollama.Client(host=str(setting.url), timeout=timeout)
        data = client.list()
        names = [model['model'] for model in data['models']]
        return names
    except Exception as e:
        print(str(e))
    return []

def chat(system_prompt:str, prompt:str, modelname:str, data:str, key:str, think:bool = False, LongTokenMode:bool = False):
    SYSTEM_PROMPT = """
        你是一个导航应用专家，了解导航应用的各个功能子系统，以及子系统对应的功能。请利用你的知识给结构化的回答。
    """
    
    if system_prompt is None:
        system_prompt = SYSTEM_PROMPT

    if data is not None:
        paragraphs = parse_file(data)
        embeddings = get_embeddings(key, "nomic-embed-text", paragraphs)
        # strongly recommended that all embeddings are generated by the same model (don't mix and match)
        prompt_embedding = client.embeddings(model="nomic-embed-text", prompt=prompt)["embedding"]
        # find most similar to each other
        most_similar_chunks = find_most_similar(prompt_embedding, embeddings)[:10]
        system_prompt = system_prompt + "\n".join(paragraphs[item[1]] for item in most_similar_chunks),

    if LongTokenMode:
        num_ctx = 40960
    else:
        num_ctx = 4096
    response = client.chat(
        model= modelname,
        messages=[
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user", 
                "content": prompt
            },
        ],
        think=think,
        options={"num_ctx": num_ctx},
    )

    # Log.info(response)
    return response["message"]["content"]

async def chat_with_tools(issue_key, prompt:str, modelname:str, tools = None, function = None, think:bool = False):
    core_data = coreData.get_core_data(issue_key)
    setting = settings.get_ollama_settings()
    timeout = setting.timeout
    client = ollama.Client(host=str(setting.url), timeout=timeout)

    try:
        SYSTEM_PROMPT = """
            你是一个导航应用专家，了解导航应用的各个功能子系统，以及子系统对应的功能。请利用你的知识给结构化的回答。
        """
        system_prompt = SYSTEM_PROMPT

        available_tools = []
        if tools:
            for tool in tools.tools:
                t = {
                    "type": "function",
                    "function": {
                        "name": tool.name,
                        "description": tool.description,
                        "parameters": tool.inputSchema
                    }
                }
                available_tools.append(t)

        messages=[
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user", 
                "content": prompt
            },
        ]

        core_data.status = coreData.Status.WATING_LLM.code
        core_data.llmStart = time.time()
        coreData.save_core_data(issue_key, core_data)
        loop = asyncio.get_event_loop()
        with ThreadPoolExecutor() as executor:
            response = await loop.run_in_executor(
                executor, 
                lambda: client.chat(
                    model=modelname,
                    messages=messages,
                    tools=available_tools,
                    think=think
                )
            )
        core_data.llmEnd = time.time()
        core_data.llmName = modelname
        core_data.llmSuccess = True if response["done"] == "True" else False
        core_data.llmTokens = response["eval_count"]
        coreData.save_core_data(issue_key, core_data)

        if response["message"].get('tool_calls'):
            if function == None:
                return 'No fucntion call'

            tool_calls = response["message"]['tool_calls']
            for call in tool_calls:
                print(call['function'].name)
                print(call['function'].arguments)
                core_data.toolName = call['function'].name
                core_data.analyzeStart = time.time()
                core_data.status = coreData.Status.WATING_TOOL.code
                coreData.save_core_data(issue_key, core_data)
                res = await function(call['function'].name, call['function'].arguments)
                core_data.analyzeEnd = time.time()
                coreData.save_core_data(issue_key, core_data)
            return res

        src = {
            "Comment":response["message"]["content"]
        }
        return json.dumps(src)
    except Exception as e:
        src = {
            "Comment":str(e)
        }
        return json.dumps(src)
